name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "master" ]

permissions:
  packages: read
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, raspberrypi]
    steps:
      - name: Pull and restart with compose
        run: |
          cd /opt/stobot
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --remove-orphans
          docker image prune -f
